apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiled
  namespace: aimm
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-aimm-tiled
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-aimm-tiled
    spec:
      affinity: {}
      containers:
        - command:
            - sleep
            - "999999"
        # - command:
        #     - tiled
        #     - serve
        #     - config
          env:
            - name: ORCID_CLIENT_ID
              value: APP-0ROS9DU5F717F7XN
            - name: TILED_CONFIG
              value: /config/main
            - name: TILED_INTERNAL_CACHE_LOG_LEVEL
              value: INFO
            - name: ORCID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: ORCID_CLIENT_SECRET
                  name: tiled
                  optional: false
            - name: TILED_SERVER_SECRET_KEYS
              valueFrom:
                secretKeyRef:
                  key: TILED_SERVER_SECRET_KEYS
                  name: tiled
                  optional: false
            - name: TILED_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-tiled-pass
                  optional: false
          image: ghcr.io/bluesky/tiled:v0.1.0a111
          imagePullPolicy: Always
          name: tiled
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 79966
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /config
              name: tiled-config
              readOnly: true
            - mountPath: /data
              name: tiled-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 94721
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /global/cfs/projectdirs/m3792/aimm/config
            type: Directory
          name: tiled-config
        - name: tiled-data
          persistentVolumeClaim:
            claimName: tiled-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tiled
  namespace: aimm
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: default
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    workload.user.cattle.io/workloadselector: deployment-aimm-tiled
  sessionAffinity: None
  type: ClusterIP