apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiled
  namespace: aimm
spec:
  selector:
  template:
    spec:
      affinity: {}
      containers:
        - command:
            - tiled
            - serve
            - config
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/aimm?authSource=admin
            - name: ORCID_CLIENT_ID
              value: APP-0ROS9DU5F717F7XN
            - name: TILED_CONFIG
              value: /config/main
            - name: TILED_INTERNAL_CACHE_LOG_LEVEL
              value: INFO
            - name: ORCID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: ORCID_CLIENT_SECRET
                  name: tiled
                  optional: false
            - name: TILED_SERVER_SECRET_KEYS
              valueFrom:
                secretKeyRef:
                  key: TILED_SERVER_SECRET_KEYS
                  name: tiled
                  optional: false
            - name: TILED_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-tiled-pass
                  optional: false
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongopass
                  optional: false
          image: ghcr.io/bluesky/tiled:v0.1.0a109
          imagePullPolicy: Always
          name: tiled
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 79966
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /config
              name: vol1
              readOnly: true
            - mountPath: /data
              name: vol2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 94721
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /global/cfs/projectdirs/m3792/aimm/config
            type: Directory
          name: vol1
        - name: vol2
          persistentVolumeClaim:
            claimName: tiled-data
