apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiled
  namespace: aimm
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-aimm-tiled
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-aimm-tiled
    spec:
      affinity: {}
      containers:
        - command:
            - sleep
            - "999999"
        # - command:
        #     - tiled
        #     - serve
        #     - config
          env:
            - name: ORCID_CLIENT_ID
              value: APP-0ROS9DU5F717F7XN
            - name: TILED_CONFIG
              value: /config/main
            - name: TILED_INTERNAL_CACHE_LOG_LEVEL
              value: INFO
            - name: ORCID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: ORCID_CLIENT_SECRET
                  name: tiled
                  optional: false
            - name: TILED_SERVER_SECRET_KEYS
              valueFrom:
                secretKeyRef:
                  key: TILED_SERVER_SECRET_KEYS
                  name: tiled
                  optional: false
            - name: TILED_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-tiled-pass
                  optional: false
          image: ghcr.io/bluesky/tiled:v0.1.0a111
          imagePullPolicy: Always
          name: tiled
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 79966
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /deploy/config # mount config from the git-sync container
              name: aimmdb-github
              subPath: main/deploy/spin/config
              readOnly: true
            - mountPath: /data
              name: tiled-data
            # - mountPath: /opt/venv/share/tiled/templates/index.html   CANNOT DO THIS UNTIL WE MERGE aimmdb PR
            #   name: aimmdb-github
            #   subPath: main/deploy/spin/web-frontend/templates/index.html
            #   readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 94721
      terminationGracePeriodSeconds: 30
      
    
      initContainers:
      # A sidecar container that downloads current main from setttings github repo
      # and places it into an emptydir volume. This gets picked up by tiled backend
      # which mountains files 
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.6
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/AI-multimodal/aimmdb.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: "/aimmdb-github"
        - name: GIT_SYNC_DEST
          value: "main"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        volumeMounts:
          - name: aimmdb-github
            readOnly: false
            mountPath: /aimmdb-github
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 79966
      volumes:
        - name: tiled-data
          persistentVolumeClaim:
            claimName: tiled-pvc
        - name: aimmdb-github
          emptyDir:
---
apiVersion: v1
kind: Service
metadata:
  name: tiled
  namespace: aimm
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: default
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    workload.user.cattle.io/workloadselector: deployment-aimm-tiled
  sessionAffinity: None
  type: ClusterIP