trees:
  - path: /
    tree: catalog
    args:
      uri: postgresql+asyncpg://tiled:${TILED_DATABASE_PASSWORD}@postgres/tiled
      writable_storage: /data/aimm/data
      # dataset_to_specs:
      #   ncm:
      #     - XAS_TFY
      #     - XAS_TEY
      #     - XAS_trans
    access_control:
      access_policy: tiled.access_policies:SimpleAccessPolicy
      args:
        provider: orcid
        access_lists:
            0000-0002-5947-6017: tiled.access_policies:ALL_ACCESS # Dan
            0000-0002-1539-0297: tiled.access_policies:ALL_ACCESS # Dylan
            0000-0002-3337-2930: tiled.access_policies:ALL_ACCESS # Eli
            0000-0002-5269-0125: tiled.access_policies:ALL_ACCESS # Alex
            0000-0003-4351-6085: tiled.access_policies:ALL_ACCESS # Deyu
            0000-0003-0666-8063: tiled.access_policies:ALL_ACCESS # Wanli
            0000-0001-5266-5408: tiled.access_policies:ALL_ACCESS # Zhu
            0000-0002-2473-0193: tiled.access_policies:ALL_ACCESS # Juan
            0000-0003-0922-1363: tiled.access_policies:ALL_ACCESS # Maria
            0000-0002-5181-9513: tiled.access_policies:ALL_ACCESS # Matt
            0000-0001-5651-8405: tiled.access_policies:ALL_ACCESS # Xiaohui
            0000-0001-9869-9005: tiled.access_policies:ALL_ACCESS # Fanchen
            0000-0003-1779-8007: tiled.access_policies:ALL_ACCESS # Mikhail
            0000-0001-8885-1552: tiled.access_policies:ALL_ACCESS # Inhui
            0000-0003-2516-2586: tiled.access_policies:ALL_ACCESS # Gihyeok
        admins:
          - 0000-0002-5947-6017 # Dan
          - 0000-0002-1539-0297 # Dylan
          - 0000-0002-2473-0193 # Juan
        public:
          - newville
          - nmc_sim
          - nmc_sim_structure
          - nmc_sim_vasp
authentication:
  allow_anonymous_access: true
  providers:
    - provider: orcid
      authenticator: tiled.authenticators:OIDCAuthenticator
      args:
        client_id: ${ORCID_CLIENT_ID}
        client_secret: ${ORCID_CLIENT_SECRET}
        # redirect_uri: https://aimm.lbl.gov/api/auth/provider/orcid/login
        public_keys:
          - kty: "RSA"
            e: "AQAB"
            use: "sig"
            kid: "production-orcid-org-7hdmdswarosg3gjujo8agwtazgkp1ojs"
            n: "jxTIntA7YvdfnYkLSN4wk__E2zf_wbb0SV_HLHFvh6a9ENVRD1_rHK0EijlBzikb-1rgDQihJETcgBLsMoZVQqGj8fDUUuxnVHsuGav_bf41PA7E_58HXKPrB2C0cON41f7K3o9TStKpVJOSXBrRWURmNQ64qnSSryn1nCxMzXpaw7VUo409ohybbvN6ngxVy4QR2NCC7Fr0QVdtapxD7zdlwx6lEwGemuqs_oG5oDtrRuRgeOHmRps2R6gG5oc-JqVMrVRv6F9h4ja3UgxCDBQjOVT1BFPWmMHnHCsVYLqbbXkZUfvP2sO1dJiYd_zrQhi-FtNth9qrLLv3gkgtwQ"
            alg: RS256
        token_uri: https://orcid.org/oauth/token
        authorization_endpoint: https://orcid.org/oauth/authorize?response_type=code&scope=openid&client_id={client_id}&redirect_uri={redirect_uri}
        confirmation_message: You have logged in with ORCID as {id}
  tiled_admins:
    - provider: orcid
      id: 0000-0003-3670-0431
uvicorn:
  host: 0.0.0.0
  port: 8000
# specs:
#   - spec: XAS_TFY
#     validator: aimmdb.validation:validate_xas_tfy
#   - spec: XAS_TEY
#     validator: aimmdb.validation:validate_xas_tey
#   - spec: XAS_trans
#     validator: aimmdb.validation:validate_xas_transmission
#   - spec: HasBatteryChargeData
#     validator: aimmdb.validation:validate_battery_charge_data
