trees:
  - path: /
    tree: tiled.examples.generated:tree
authentication:
  allow_anonymous_access: false
  authenticator: tiled.authenticators:OIDCAuthenticator
  args:
    client_id: ${ORCID_CLIENT_ID}
    client_secret: ${ORCID_CLIENT_SECRET}
    redirect_uri: https://aimm.lbl.gov/static/login.html
    public_keys:
      - kty: "RSA"
        e: "AQAB"
        use: "sig"
        kid: "production-orcid-org-7hdmdswarosg3gjujo8agwtazgkp1ojs"
        n: "jxTIntA7YvdfnYkLSN4wk__E2zf_wbb0SV_HLHFvh6a9ENVRD1_rHK0EijlBzikb-1rgDQihJETcgBLsMoZVQqGj8fDUUuxnVHsuGav_bf41PA7E_58HXKPrB2C0cON41f7K3o9TStKpVJOSXBrRWURmNQ64qnSSryn1nCxMzXpaw7VUo409ohybbvN6ngxVy4QR2NCC7Fr0QVdtapxD7zdlwx6lEwGemuqs_oG5oDtrRuRgeOHmRps2R6gG5oc-JqVMrVRv6F9h4ja3UgxCDBQjOVT1BFPWmMHnHCsVYLqbbXkZUfvP2sO1dJiYd_zrQhi-FtNth9qrLLv3gkgtwQ"
        alg: RS256
    token_uri: https://orcid.org/oauth/token
    authorization_endpoint: https://orcid.org/oauth/authorize?client_id={client_id}&response_type=code&scope=openid&redirect_uri={redirect_uri}
    confirmation_message: You have logged with ORCID.
access_control:
  # Unauthenticated users can see some public datasets, but
  # not everything.
  access_policy: tiled.trees.in_memory:SimpleAccessPolicy
  args:
    access_lists:
      # Map ORCID to list of paths they can see, or ALL as shown below.
      0000-0002-5947-6017: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Dan sees all
      0000-0003-3670-0431: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Joe sees all
      0000-0002-1539-0297: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Dylan sees all
      0000-0002-3337-2930: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Eli sees all
      0000-0002-5269-0125: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Alex sees all
      0000-0003-4351-6085: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Deyu sees all
      0000-0003-0666-8063: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Wanli sees all
      0000-0001-5266-5408: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Zhu sees all
      0000-0002-2473-0193: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Juan sees all
      0000-0003-0922-1363: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Maria sees all
      0000-0002-5181-9513: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Matt sees all
      0000-0001-5651-8405: tiled.trees.in_memory:SimpleAccessPolicy.ALL  # Xiaohui sees all
database_uri: "postgresql://tiled:${TILED_DATABASE_PASSWORD}@postgres/tiled"
uvicorn:
  host: 0.0.0.0
  port: 8000
  proxy-headers: true
media_types:
  node:
    application/x-hdf5: aimmdb:serialize_hdf5

      #  - path: /
      #    tree: aimmdb:AIMMTree.from_uri
      #    args:
      #      uri: ${MONGO_URI}
      #      username: root
      #      password: ${MONGO_PASSWORD}
      #      tree_collection_name: "tree"
      #      data_collection_name: "measurements"
