trees:
  - path: /
    tree: catalog
    args:
      uri: ./catalog.db
      writable_storage: /data/aimm/data
      # dataset_to_specs:
      #   ncm:
      #     - XAS_TFY
      #     - XAS_TEY
      #     - XAS_trans
    access_control:
      access_policy: aimmdb.access:DatasetAccessPolicy
      args:
        provider: toy
        access_lists:
          joe:
            default: rw
          dan:
            default: r
authentication:
  allow_anonymous_access: false
  providers:
    - provider: toy
      authenticator: tiled.authenticators:DictionaryAuthenticator
      args:
        users_to_passwords:
          joe: abc123
          dan: abc123
  tiled_admins:
    - provider: toy
      id: joe
# specs:
#   - spec: XAS_TFY
#     validator: aimmdb.validation:validate_xas_tfy
#   - spec: XAS_TEY
#     validator: aimmdb.validation:validate_xas_tey
#   - spec: XAS_trans
#     validator: aimmdb.validation:validate_xas_transmission
#   - spec: HasBatteryChargeData
#     validator: aimmdb.validation:validate_battery_charge_data
