trees:
  - path: /
    tree: aimmdb:AIMMTree.from_uri
    args:
      uri: ${MONGO_URI}
      username: root
      password: ${MONGO_PASSWORD}
    access_control:
      access_policy: aimmdb:AIMMAccessPolicy
      args:
        provider: toy
        access_lists:
          joe: aimmdb:AIMMAccessPolicy.READWRITE
          dan: aimmdb:AIMMAccessPolicy.READ
authentication:
  allow_anonymous_access: false
  providers:
    - provider: toy
      authenticator: tiled.authenticators:DictionaryAuthenticator
      args:
        users_to_passwords:
          joe: abc123
          dan: abc123
  tiled_admins:
    - provider: toy
      id: joe
media_types:
  node:
    application/x-hdf5: aimmdb:serialize_hdf5
allow_origins:
  - '*'
