trees:
  - path: /
    tree: aimmdb:MongoXASTree.from_uri
    args:
      uri: ${MONGO_URI}
      username: root
      password: ${MONGO_PASSWORD}
      collection_name: "spike"
authentication:
  allow_anonymous_access: false
  single_user_api_key: abc
media_types:
  node:
    application/x-hdf5: aimmdb:serialize_hdf5
