trees:
  - path: /
    tree: aimmdb:AIMMTree.from_uri
    args:
      uri: ${MONGO_URI}
      username: root
      password: ${MONGO_PASSWORD}
      tree_collection_name: "tree"
      data_collection_name: "measurements"
authentication:
  allow_anonymous_access: true
media_types:
  node:
    application/x-hdf5: aimmdb:serialize_hdf5
allow_origins:
  - '*'
