trees:
  - path: /xas_feff_nmc
    tree: tree:MongoXASTree.from_uri
    args:
      uri: ${MONGODB_URI}
      username: "root"
      password: ${MONGODB_PASSWORD}
      collection_name: "xas_feff_nmc"
  - path: /newville
    tree: tree:MongoXASTree.from_uri
    args:
      uri: ${MONGODB_URI}
      username: "root"
      password: ${MONGODB_PASSWORD}
      collection_name: "newville"
  - path: /torrisi
    tree: tree:MongoXASTree.from_uri
    args:
      uri: ${MONGODB_URI}
      username: "root"
      password: ${MONGODB_PASSWORD}
      collection_name: "torrisi"
  - path: /heald
    tree: tree:MongoXASTree.from_uri
    args:
      uri: ${MONGODB_URI}
      username: "root"
      password: ${MONGODB_PASSWORD}
      collection_name: "heald_normalized"
  - path: /heald_unnormalized
    tree: tree:MongoXASTree.from_uri
    args:
      uri: ${MONGODB_URI}
      username: "root"
      password: ${MONGODB_PASSWORD}
      collection_name: "heald_unnormalized"
  - path: /wanli
    tree: tree:MongoXASTree.from_uri
    args:
      uri: ${MONGODB_URI}
      username: "root"
      password: ${MONGODB_PASSWORD}
      collection_name: "wanli"
